server:
  port: 8084
mybatis:
  mapper-locations: classpath:mybatis/mappers/*.xml
  config-location: classpath:mybatis/mybatis-config.xml
spring:
  thymeleaf:
    cache: false
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
    check-template-location: true
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${RDS_POST_URL}
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true




